trigger:
  branches:
    include:
      - main  # substitua 'main' pelo nome do seu branch principal, se necessário

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python scripts/train_model.py
  displayName: 'Train Model'

- script: |
    python scripts/evaluate_model.py
  displayName: 'Evaluate Model'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'models'
    ArtifactName: 'model'