trigger:
  branches:
    include:
<<<<<<< HEAD
      - main
=======
      - main  # substitua 'main' pelo nome do seu branch principal, se necessário
>>>>>>> 980e11e4b0503ee55b77b0a37b3163c40b2551cd

pool:
  vmImage: 'ubuntu-latest'

steps:
<<<<<<< HEAD
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python scripts/train_model.py
  displayName: 'Train Model'

- script: |
    python scripts/evaluate_model.py
  displayName: 'Evaluate Model'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'models'
    ArtifactName: 'model'
=======
- script: echo 'Hello, World!'
  displayName: 'Print Hello World'
>>>>>>> 980e11e4b0503ee55b77b0a37b3163c40b2551cd
