trigger:
  branches:
    include:
      - main  # substitua 'main' pelo nome do seu branch principal, se necessário

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo 'Hello, World!'
  displayName: 'Print Hello World'
